name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: configure
#       run: ./configure
    - name: make
      run: cd code/4r-in1a/tp1 && make && chmod 777 test && ./test
    # - name: make check
    #   run: cd code/4r-in1a/tp1 && make check
    # - name: make distcheck
    #   run: cd code/4r-in1a/tp1 && make distcheck
